expect "@" "CONNECT <SOURCES>\r"

expect "@" "MACRO\n"
expect "*" "STENEX=TTY:,STENEX,TTY:\r"
expect "\n" "UNIVERSAL STENEX\rINTERF==0\r\032"
expect "\n" "END\r"
expect "*" "MACRO=MACRO\r"
expect "*" "HELPER=HELPER\r"
expect "*" "LOADER=LOADER\r"
expect "*" "CCL=CCL\r"
expect "*" "DLUSER=DLUSER\r"
expect "*" "JOBDAT=JOBDAT\r"
expect "*" "PAT=PAT\r"
expect "*" "TECO=TECO\r"
expect "*" "\032"

expect "@" "LOAD MACRO\r"
expect "@" "SSAVE <SUBSUS>MACRO.SAV\r"
expect "@" "LOAD LOADER\r"
expect "@" "SSAVE <SUBSUS>LOADER.SAV\r"
expect "@" "LOADER\r"
expect "*" "/S/B/1H/700000H=r"
expect "*" "PAT\032"
expect "@" "SAVE <SUBSYS>PAT.SAV\r"
expect "@" "START\r"
expect "@" "GET <SUBSYS>PAT.SAV\r"
expect "@" "DDT\r"
expect "\n" "MAKEPF\032G"
expect "\n" "\003"
expect "@" "RENAME PA1050.SAV <SUBSYS>\r"
expect "@" "LOAD CCL\r"
expect "@" "SSAVE <SUBSUS>CCL.SAV\r"
expect "@" "LOAD DLUSER\r"
expect "@" "SAVE <SUBSUS>DLUSER.SAV\r"

expect "@" "FAIL\r"
expect "*" "FAIL=FAIL\r"
expect "*" "DUMPER=DUMPER\r"
expect "*" "\003"
expect "@" "LOAD FAIL\r"
expect "@" "SSAVE <SUBSUS>FAIL.SAV\r"
expect "@" "LOAD DUMPER\r"
expect "@" "SAVE <SUBSUS>DUMPER.SAV\r"

expect "@" "DEL *.REL\r"
expect "@" "EXPUNGE\r"
